# Generated by Django 3.0.14 on 2022-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20220531_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.TextField()),
                ('headimage', models.ImageField(upload_to='about/')),
                ('footimage', models.ImageField(upload_to='about/')),
                ('heading', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
    ]
