# Generated by Django 3.2.9 on 2022-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20220615_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
