# Generated by Django 3.2.9 on 2022-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_properties_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeimgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeimage', models.ImageField(upload_to='home/')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
